#!/usr/bin/env php
<?php
/*
 * Yii2 Autocomplete Helper
 *
 * Vitaliy IIIFX Khomenko (c) 2016
 */

echo 'Yii2 Autocomplete Helper... ';

use iiifx\Yii2\Autocomplete\Builder;
use iiifx\Yii2\Autocomplete\Reader;

$vendorPath = __DIR__ . '/../..';
$projectPath = $vendorPath . '/..';

require $vendorPath . '/autoload.php';
require $vendorPath . '/yiisoft/yii2/Yii.php';

$basic = new Reader( [
    'path' => $projectPath,
    'files' => [
        'config/web.php',
        'config/console.php',
    ],
] );

if ( $basic->isValid() ) {
    $result = ( new Builder( [
        'reader' => $basic,
    ] ) )->build( $projectPath . '/autocomplete.php' );

    die( ( $result ? 'Done.' : 'Fail.' ) . PHP_EOL );
}

$advanced = new Reader( [
    'path' => $projectPath,
    'files' => [
        'backend/config/main.php',
        'common/config/main.php',
        'console/config/main.php',
        'frontend/config/main.php',
    ],
] );

if ( $advanced->isValid() ) {
    $result = ( new Builder( [
        'reader' => $advanced,
    ] ) )->build( $projectPath . '/autocomplete.php' );

    die( ( $result ? 'Done.' : 'Fail.' ) . PHP_EOL );
}

die( 'Project config not found' . PHP_EOL );