#!/usr/bin/env php
<?php
/*
 * Yii2 Autocomplete Helper
 *
 * Vitaliy IIIFX Khomenko (c) 2016
 */

use iiifx\Yii2\Autocomplete\Builder;
use iiifx\Yii2\Autocomplete\Reader;

define( 'VENDOR_PATH', __DIR__ . '/../../' );
define( 'ROOT_PATH', __DIR__ . '/../../../' );

require __DIR__ . VENDOR_PATH . 'autoload.php';
require( __DIR__ . VENDOR_PATH . 'yiisoft/yii2/Yii.php' );

( new Builder( [
    'reader' => new Reader( [
        'path' => ROOT_PATH,
        'files' => [
            'config/web.php',
            'config/console.php',
        ],
    ] ),
] ) )->build(); # ->build( ROOT_PATH . 'autocomplete.php')
