#!/usr/bin/env php
<?php
/*
 * Yii2 Autocomplete Helper
 *
 * Vitaliy IIIFX Khomenko (c) 2016
 */

# Только для процесса разработки

use iiifx\Yii2\Autocomplete\Builder;
use iiifx\Yii2\Autocomplete\Reader;

/** @var \Composer\Autoload\ClassLoader $loader */

$loader = require __DIR__ . '/../../autoload.php';
require( __DIR__ . '/../../yiisoft/yii2/Yii.php' );

( new Builder( [
    'reader' => new Reader( [
        'path' => __DIR__,
        'files' => [
            'config/web.php',
            'config/console.php',
        ],
    ] ),
] ) )->build();
